### ISSUE TITLE
Login with facebook

### ISSUE THREAD

**Issue by michael-braun** [TobitSoftware/chayns-web-light#6]
I can't use the facebook-login on ChaynsWebLight. A wait cursor is shown, but the login window does not open.
The console shows: _Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings._

My URL is: [https://chayns2.tobit.com/ChaynsWebLight/v2/?locationId=116240&tappId=361359&backgroundColor=000000](https://chayns2.tobit.com/ChaynsWebLight/v2/?locationId=116240&tappId=361359&backgroundColor=000000)

**Comment by meldau** [comment]
typical problem after changing domain for chayns. The new domain is not known within the facebook app... So facebook - correctly - avoid a login

**Comment by michael-braun** [comment]
Thank you for explaining it. Yes, it is correct that than facebook avoid a login, but I think that the facebook-login should work in the LIVE-Version of ChaynsWebLight (like referred in the Wiki), which is hosted by Tobit.

**Comment by kmathmann** [comment]
Thanks for your report.
The location 116240 should now be able to use the facebook login.
 
This is a known issue. We currently work at a solution to make the facebook login possible for all chayns sites.
